baseURL = 'https://duykhanh369.github.io/22DTHC5-7_KhanhLDD_Blog/'
languageCode = 'vi'
title = 'Blog Lập Trình - KhanhLDD'
theme = 'minimal-blog'
publishDir = 'docs'
canonifyURLs = true
relativeURLs = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  authorName = "Le Dang Duy Khanh"
  subtitle = "Lập trình viên Java & JavaScript"
  bio = "Chào mừng bạn đến với blog cá nhân của tôi! Tôi chia sẻ kiến thức về lập trình mạng, Java và JavaScript."
  description = "Blog chia sẻ kiến thức về lập trình Java và JavaScript"
  avatar = "/images/avatar.jpg"

  [params.social]
    github = "https://github.com/DuyKhanh369"
    email = "Ledangduykhanh2609@gmail.com"
